-- Prescription
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Abilify', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Acamprosate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Acarbose', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Acetaminophen', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Acyclovir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Adderall', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Admelog', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Advair', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Advil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Albendazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Albuterol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'ALENDRONATE', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Aleve', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Alogliptin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Alprazolam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amiodarone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amitriptyline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amlodine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amlodipine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amoxicillin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Amphetamine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Aspirin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Aripiprazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Armodafinil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Atarvastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Atazanavir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Atenolol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Atomoxetine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Atorvastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Azelastine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Baclofen', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Basgalar', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Belsomra', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Benzonatrate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Benztropine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Biotin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Breztri', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Briviact', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Buprenorphine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Bupropion', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Buspeirone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Buspirone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cabergoline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Candesartan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cannabis', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Captopril', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Carbamazepine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Carvedilol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cefuroxime', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Celecoxib', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cephalexin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cetirizine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Chantix', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Chlordiazepoxide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cialis', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ciprofloxacin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Citalopram', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Claravis', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clarithromycin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Claritin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clindamycin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clomiphene', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clonazepam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clondine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clonidine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clopidogrel', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Chlorthalidone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clotrimazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Clozapine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Colchicine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Colestipole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cyanocobalamin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Cyclobenzaprine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Delsym', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Depakote', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Descovy', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Desvenlafaxine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Diazepam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Diclofenac', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Dicyclomine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Digoxin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Diltiazem', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Diphenhydramine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Diphenoxylate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Disulfiram', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Donepezil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Doxazosin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Doxepin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Doxycycline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Duloxetine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Effexor', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Eliquis', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Enalapril', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Epclusa', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Epinephrine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Erythromycin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Escitalopram', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Esomeprazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Eszopiclone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Etodolac', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Euthyox', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Excedrin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Famotidine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Farxiga', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Fenofibrate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ferrous sulfate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Finasteride', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Flovent', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Fluconazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Fluoxetine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Fluticasone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Folic Acid', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Furosemide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Gabapentin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'GasX', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Gemfibrozil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Glimepiride', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Glipizide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Glycopyrrolate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Guanfacine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Haloperidol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Humalog', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydralazine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydrochlorothiazide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydrocodone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydrocodone-Acetaminophen', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydrocortisone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydromorphone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydroxychloroquine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Hydroxyzine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Incruse', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Indomethacin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Insulin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Isentress', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Isosorbide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Janumet', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Januvia', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Jardiance', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Keppra', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ketorolac', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Labetalol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lamotrigine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lansoprazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lantus', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Latuda', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Letrozole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Levemir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Levetiracetam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Levofloxacin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Levothroxine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lexapro', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lidocaine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Linzess', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Liothyronine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lisinopril', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lithium', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Loperamide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Loratadine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lorazepam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Losartan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lovastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Lyrica', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Magnesium', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Mavyret', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Meclizine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Medrol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Medroxyprogesterone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Melatonin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Meloxicam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Metaxalone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Metformin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methadone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methimazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methylprednisolone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methocarbamol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methotrexate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Methylphenidate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Metoclopramide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Metoprolol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Metronidazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Minocycline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'MiraLax', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Mirtazapine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Modafinil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Montelukast', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Morphine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Moxifloxacin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Mucinex', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Mupirocin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Mirabegron', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nabumetone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Naloxone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Naltrexone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Namzaric', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Naproxen', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Narcan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nicotine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nicotine Gum', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nicotine Patch', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nicotrol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nitrofurantoin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nitroglycerin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Nortriptyline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'NovoLog', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'NyQuil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ofloxacin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Olanzapine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Olmesartan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Omeprazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ondansetron', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Oxcarbazepine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Oxybutynin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Oxycodone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Oxycontin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ozempic', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Paliperidone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pantoprazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Paroxetine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Penicillin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pepcid', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Perphenazine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Phenazopyridine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Phenobarbital', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Phentermine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Phenytoin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pioglitazone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Polyethylene', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Polymyxin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Potassium', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pradaxa', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pramipexole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Prasugrel', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pravastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Prazosin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Prednisone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Pregabalin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Prilosec', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Promethazine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Propranolol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Quetiapine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Raltegravir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ranitidine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Rexulti', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Risperidone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ritonavir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Rizatriptan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ropinirole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Rosuvastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Saphris', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Semglee', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Seroquel', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sertraline', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sildenafil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Simvastatin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sinex', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Spironolactone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Spiriva', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sprintec', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Suboxone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sucralfate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sulfamethoxazole', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sulindac', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Sumatriptan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Symbicort', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Synthroid', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tadalafil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tamsulosin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tegretol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Temazepam', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Terazosin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Terbinafine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Testosterone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tivicay', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tizanidine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tobramycin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Topiramate', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Torsemide', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Toujeo', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tradjenta', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tramadol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tranexamic Acid', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Trazodone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Triamcinolone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Triamterene', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Trifluoperazine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'rihexyphenidyl', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Trintellix', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Trulicity', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Tylenol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Valacyclovir', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Valsartan', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Venlafaxine', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ventolin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Verapamil', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Victoza', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Viibryd', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Vivitrol', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Vraylar', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Vyvanse', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Wellbutrin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Warfarin', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Xarelto', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Xopenex', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Xtampza', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Zaleplon', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Zinc', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Ziprasidone', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Zoloft', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Zolpidem', 0, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES (  'Zyrtec', 0, NOW(), NOW());

-- OTC
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Acetaminophen', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Advil', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Aleve', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Alka Seltzer', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Allegra', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Anbesol', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Antacid', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Anti-diarrheal', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Aspirin', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Beano', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Benadryl', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Biotin', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Carditone', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Clartin', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('ClearLax', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Creatine', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('DayQuil', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Diphenhydramine', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Famatodine', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Headache', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Hydrocortisone', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Ibuprofen', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Imodium', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Loratidine', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Magnesium', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Melatonin', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Midol', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Milk of Magnesia', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Miralax', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Naproxen', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Nicorette', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Novolin', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Stool Softener', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Tums', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Tylenol', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Xyzal', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Zinc', 1, NOW(), NOW());
INSERT INTO DrugNames (Drug,  OTC, Created, Updated) VALUES ('Zyrtec', 1, NOW(), NOW());
